# Generated by Django 4.2.14 on 2024-08-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('ip', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('created_date', models.DateTimeField()),
                ('created_by', models.CharField(max_length=32)),
                ('updated_by', models.CharField(max_length=32)),
            ],
        ),
    ]
