# Generated by Django 3.2.25 on 2024-08-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='a',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
