# Generated by Django 3.2.25 on 2024-08-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_info_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='a',
        ),
    ]
